# SPDX-FileCopyrightText: 2018 CERN.
# SPDX-License-Identifier: MIT

[pytest]
addopts = --isort --pydocstyle --pycodestyle --doctest-glob="*.rst" --doctest-modules --cov=invenio_iiif --cov-report=term-missing
testpaths = tests invenio_iiif
